version: "3.9"

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    working_dir: /home/pptruser
    restart: always
    ports:
      - 80:80
    volumes:
      - .:/home/pptruser
    networks:
      - whats-app-bot


networks:
  whats-app-bot:
    driver: bridge
